CREATE DATABASE IF NOT EXISTS omrstatisticsdb;
USE omrstatisticsdb;
DROP TABLE IF EXISTS Polymorphism;
DROP TABLE IF EXISTS Hierarchy;
DROP TABLE IF EXISTS Override;
DROP TABLE IF EXISTS Function;
DROP TABLE IF EXISTS File;
DROP TABLE IF EXISTS Class;
